environment:
  PYTHON: "C:\\Python27-x64"
  matrix:
    - nodejs_version: '8'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\\npm;%PATH%
  - npm install winax --python=%PYTHON%\\python.exe
  - npm rebuild winax --runtime=electron --target=1.7.15 --disturl=https://atom.io/download/atom-shell --build-from-source
matrix:
  fast_finish: true
build: off
shallow_clone: true
cache:
  - '%APPDATA%\npm-cache'
artifacts:
  - path: "node_modules\\winax"
